// <auto-generated />
using System;
using CodingChallenge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodingChallenge.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.BoardComponent", b =>
                {
                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("BoardComponents");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.OrderBoard", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId", "BoardId");

                    b.HasIndex("BoardId");

                    b.ToTable("OrderBoards");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.BoardComponent", b =>
                {
                    b.HasOne("CodingChallenge.Api.Domain.Entities.Board", "Board")
                        .WithMany("BoardComponents")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodingChallenge.Api.Domain.Entities.Component", "Component")
                        .WithMany("BoardComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.OrderBoard", b =>
                {
                    b.HasOne("CodingChallenge.Api.Domain.Entities.Board", "Board")
                        .WithMany("OrderBoards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodingChallenge.Api.Domain.Entities.Order", "Order")
                        .WithMany("OrderBoards")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.Board", b =>
                {
                    b.Navigation("BoardComponents");

                    b.Navigation("OrderBoards");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.Component", b =>
                {
                    b.Navigation("BoardComponents");
                });

            modelBuilder.Entity("CodingChallenge.Api.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderBoards");
                });
#pragma warning restore 612, 618
        }
    }
}
