name: Pipeline

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  sbom:
    name: SBOM
    needs: ci
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/sbom.yml

  cd:
    name: CD
    needs: sbom
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/cd.yml
